class BooksTester{

   public static void main(String book[]){
	   Books book1 = new Books();
       book1.name = "The Great Gatsby";
       book1.author = "F. Scott Fitzgerald";
       book1.genre = "Fiction";
	   book1.price = 100;
	   
	   System.out.println("1st copy of book :");
	   System.out.println( "Book :"+ book1.name +"\n "+"Author :"+ book1.author +" \n"+"genre :"+ book1.genre +"\n "+"price :"+ book1.price );
	   book1.gainKnowledge();
	   System.out.println("-------------------------------------------------------------------");	
	   Books book2 = new Books();
       book2.name = "To Kill a Mockingbird";
       book2.author = "Harper Lee";
       book2.genre = "Fiction";
	   book2.price = 150;
	   book2.gainKnowledge();
	   System.out.println("2nd copy of book :");
	   System.out.println("Book :"+ book2.name +"\n "+"Author :"+ book2.author +" \n"+"genre :"+ book2.genre +"\n "+"price :"+ book2.price ); 
	   System.out.println("-------------------------------------------------------------------");
	     
	   Books book3 = new Books();
       book3.name = "1984";
       book3.author = "George Orwell";
       book3.genre = "Fiction";
	   book3.price = 200;
	   book3.gainKnowledge();
	   System.out.println("3rd copy of book :");
	   System.out.println( "Book :"+ book3.name +"\n "+"Author :"+ book3.author +" \n"+"genre :"+ book3.genre +"\n "+"price :"+ book3.price ); 
	   System.out.println("-------------------------------------------------------------------");
	   Books book4 = new Books();
       book4.name = "Pride and Prejudice";
       book4.author = "Jane Austen";
       book4.genre = "Fiction";
	   book4.price = 250;
	   book4.gainKnowledge();
	   System.out.println("4th copy of book :");
	   System.out.println("Book :"+  book4.name +"\n "+"Author :"+ book4.author +" \n"+"genre :"+ book4.genre +"\n "+"price :"+book4.price ); 
	    System.out.println("-------------------------------------------------------------------");    
	    Books book5 = new Books();
       book5.name = "The Catcher in the Rye";
       book5.author = "J.D. Salinger";
       book5.genre = "Fiction";
	   book5.price = 300;
	   book5.gainKnowledge();
	   System.out.println("5th copy of book :");
	   System.out.println( "Book :"+ book5.name +"\n "+"Author :"+ book5.author +" \n"+"genre :"+ book5.genre +"\n "+"price :"+ book5.price ); 
	    System.out.println("-------------------------------------------------------------------");
		Books book6 = new Books();
       book6.name = "Harry Potter and the Sorcerer";
       book6.author = "J.K. Rowling";
       book6.genre = "Fantasy";
	   book6.price = 350;
	   book6.gainKnowledge();
	   System.out.println("6th copy of book :");
	   System.out.println("Book :"+  book6.name +"\n "+ "Author :"+book6.author +" \n"+"genre :"+ book6.genre +"\n "+"price :"+ book6.price ); 
	    System.out.println("-------------------------------------------------------------------");
	    Books book7 = new Books();
       book7.name = "The Hobbit";
       book7.author = "J.R.R. Tolkien";
       book7.genre = "Fantasy";
	   book7.price = 400;
	   book7.gainKnowledge();
	   System.out.println("7th copy of book :");
	   System.out.println("Book :"+  book7.name +"\n "+"Author :"+ book7.author +" \n"+"genre :"+ book7.genre +"\n "+"price :"+ book7.price ); 
	    System.out.println("-------------------------------------------------------------------");
	    Books book8 = new Books();
       book8.name = "The Da Vinci Code";
       book8.author = "Dan Brown";
       book8.genre = "Thriller";
	   book8.price = 450;
	   book8.gainKnowledge();
	   System.out.println("8th copy of book :");
	   System.out.println("Book :"+  book8.name +"\n "+"Author :"+ book8.author +" \n"+"genre :"+ book8.genre +"\n "+"price :"+ book8.price ); 
	    System.out.println("-------------------------------------------------------------------");
	    Books book9 = new Books();
       book9.name = "Gone Girl";
       book9.author = "Gillian Flynn";
       book9.genre = "Mystery";
	   book9.price = 500;
	   book9.gainKnowledge();
	   System.out.println("9th copy of book :");
	   System.out.println("Book :"+  book9.name +"\n "+"Author :"+ book9.author +" \n"+"genre :"+ book9.genre +"\n "+"price :"+ book9.price ); 
	    System.out.println("-------------------------------------------------------------------");
	    Books book10 = new Books();
       book10.name = "The Alchemist";
       book10.author = "Paulo Coelho";
       book10.genre = "Fiction";
	   book10.price = 550;
	   book10.gainKnowledge();
	   System.out.println("10th copy of book :");
	   System.out.println("Book :"+  book10.name +"\n "+"Author :"+ book10.author +" \n"+"genre :"+ book10.genre +"\n "+"price :"+ book10.price ); 
   }
}
